/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [13-1:0] M_beta_guess_out;
  wire [13-1:0] M_beta_check_answer_out;
  wire [8-1:0] M_beta_led_1;
  wire [8-1:0] M_beta_led_2;
  wire [8-1:0] M_beta_led_3;
  wire [8-1:0] M_beta_led_4;
  wire [8-1:0] M_beta_led_5;
  wire [8-1:0] M_beta_led_6;
  wire [8-1:0] M_beta_led_7;
  wire [8-1:0] M_beta_led_8;
  beta_2 beta (
    .clk(clk),
    .rst(rst),
    .guess_out(M_beta_guess_out),
    .check_answer_out(M_beta_check_answer_out),
    .led_1(M_beta_led_1),
    .led_2(M_beta_led_2),
    .led_3(M_beta_led_3),
    .led_4(M_beta_led_4),
    .led_5(M_beta_led_5),
    .led_6(M_beta_led_6),
    .led_7(M_beta_led_7),
    .led_8(M_beta_led_8)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = 8'h00;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    io_led = 24'h000000;
    io_seg = 8'hff;
    io_sel = 4'hf;
    
    case (io_dip[0+1+0-:1])
      1'h1: begin
        io_led[0+7-:8] = M_beta_led_7;
        io_led[8+7-:8] = M_beta_led_8;
      end
    endcase
  end
endmodule
